apiVersion: v1
kind: ServiceAccount
metadata:
  name: quiz-site
  namespace: quiz-app
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quiz-site-role
  namespace: quiz-app
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quiz-site-rolebinding
  namespace: quiz-app
subjects:
  - kind: ServiceAccount
    name: quiz-site
    namespace: quiz-app
roleRef:
  kind: Role
  name: quiz-site-role
  apiGroup: rbac.authorization.k8s.io
